version: "3.9"
services:
  envoy:
    image: envoyproxy/envoy:v1.21.1
    command: envoy -c /config/envoy.json
    volumes:
      - ${BOOTSTRAP_ENVOY_FILE:-./config/local/envoy.json}:/config/envoy.json
    ports:
      - "10000:10000"
  mysql-server:
    image: mysql:8.0
    volumes:
      - mysql-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DCS_DATABASE}
  nats-server:
    image: nats:2.7-alpine
    ports:
      - "8222:8222"
    command: -c /config/server.conf
    volumes:
      - ./config/nats-server.conf:/config/server.conf
      - ./pki/nats-server/server.crt:/config/pki/server.crt
      - ./pki/nats-server/server.key:/config/pki/server.key
      - ./pki/root.crt:/config/pki/root.crt
  pdp:
    image: ghcr.io/safedep/gateway:latest
    command: pdp-server
    volumes:
      - ${BOOTSTRAP_CONFIG_FILE:-./config/local/gateway.json}:/config/gateway.json
      - ${BOOTSTRAP_BASIC_AUTH_DIR:-./config/local/auth}:/auth
      - ./policies:/policies
      - ./pki/pdp/server.crt:/config/pki/server.crt
      - ./pki/pdp/server.key:/config/pki/server.key
      - ./pki/root.crt:/config/pki/root.crt
    environment:
      GLOBAL_CONFIG_PATH: /config/gateway.json
      PDP_POLICY_PATH: /policies
      SERVICE_TLS_CERT: /config/pki/server.crt
      SERVICE_TLS_KEY: /config/pki/server.key
      SERVICE_TLS_ROOT_CA: /config/pki/root.crt
      PDS_HOST: pds
      PDS_PORT: 9002
      PDP_KAFKA_PONGO_BOOTSTRAP_SERVERS: kafka1-host:9092
      PDP_KAFKA_PONGO_SCHEMA_REGISTRY_URL: http://kafka1-host:8081
      APP_SERVICE_OBS_ENABLED: ${PDP_SERVICE_OBS_ENABLED:-true}
      APP_SERVICE_NAME: ${PDP_SERVICE_NAME:-pdp}
      APP_SERVICE_ENV: ${PDP_SERVICE_ENV:-development}
      APP_OTEL_EXPORTER_OTLP_ENDPOINT: ${COMMON_OTEL_EXPORTER_OTLP_ENDPOINT:-localhost:4317}
    extra_hosts:
      kafka1-host: ${KAFKA_PONGO_HOST}
  tap:
    image: ghcr.io/safedep/gateway:latest
    command: tap-server
    volumes:
      - ${BOOTSTRAP_CONFIG_FILE:-./config/local/gateway.json}:/config/gateway.json
      - ./pki/tap/server.crt:/config/pki/server.crt
      - ./pki/tap/server.key:/config/pki/server.key
      - ./pki/root.crt:/config/pki/root.crt
    environment:
      GLOBAL_CONFIG_PATH: /config/gateway.json
      SERVICE_TLS_CERT: /config/pki/server.crt
      SERVICE_TLS_KEY: /config/pki/server.key
      SERVICE_TLS_ROOT_CA: /config/pki/root.crt
      APP_SERVICE_OBS_ENABLED: ${TAP_SERVICE_OBS_ENABLED:-true}
      APP_SERVICE_NAME: ${TAP_SERVICE_NAME:-tap}
      APP_SERVICE_ENV: ${TAP_SERVICE_ENV:-development}
      APP_OTEL_EXPORTER_OTLP_ENDPOINT: ${COMMON_OTEL_EXPORTER_OTLP_ENDPOINT:-localhost:4317}
  dcs:
    depends_on:
      - mysql-server
    image: ghcr.io/safedep/gateway:latest
    command: dcs-server
    volumes:
      - ${BOOTSTRAP_CONFIG_FILE:-./config/local/gateway.json}:/config/gateway.json
      - ./pki/dcs/server.crt:/config/pki/server.crt
      - ./pki/dcs/server.key:/config/pki/server.key
      - ./pki/root.crt:/config/pki/root.crt
    environment:
      GLOBAL_CONFIG_PATH: /config/gateway.json
      SERVICE_TLS_CERT: /config/pki/server.crt
      SERVICE_TLS_KEY: /config/pki/server.key
      SERVICE_TLS_ROOT_CA: /config/pki/root.crt
      MYSQL_SERVER_HOST: mysql-server
      MYSQL_SERVER_PORT: 3306
      MYSQL_DATABASE: ${MYSQL_DCS_DATABASE}
      MYSQL_USER: ${MYSQL_DCS_USER}
      MYSQL_PASSWORD: ${MYSQL_DCS_PASSWORD}
      APP_SERVICE_OBS_ENABLED: ${DCS_SERVICE_OBS_ENABLED:-true}
      APP_SERVICE_NAME: ${DCS_SERVICE_NAME:-dcs}
      APP_SERVICE_ENV: ${DCS_SERVICE_ENV:-development}
      APP_OTEL_EXPORTER_OTLP_ENDPOINT: ${COMMON_OTEL_EXPORTER_OTLP_ENDPOINT:-localhost:4317}
  pds:
    depends_on:
      - mysql-server
      - dcs
    image: ghcr.io/safedep/gateway:latest
    command: pds-server
    volumes:
      - ${BOOTSTRAP_CONFIG_FILE:-./config/local/gateway.json}:/config/gateway.json
      - ./pki/pds/server.crt:/config/pki/server.crt
      - ./pki/pds/server.key:/config/pki/server.key
      - ./pki/root.crt:/config/pki/root.crt
    environment:
      GLOBAL_CONFIG_PATH: /config/gateway.json
      PDS_SERVER_NAME: pds
      SERVICE_TLS_CERT: /config/pki/server.crt
      SERVICE_TLS_KEY: /config/pki/server.key
      SERVICE_TLS_ROOT_CA: /config/pki/root.crt
      MYSQL_SERVER_HOST: mysql-server
      MYSQL_SERVER_PORT: 3306
      MYSQL_DATABASE: ${MYSQL_DCS_DATABASE}
      MYSQL_USER: ${MYSQL_DCS_USER}
      MYSQL_PASSWORD: ${MYSQL_DCS_PASSWORD}
      APP_SERVICE_OBS_ENABLED: ${PDS_SERVICE_OBS_ENABLED:-true}
      APP_SERVICE_NAME: ${PDS_SERVICE_NAME:-pds}
      APP_SERVICE_ENV: ${PDS_SERVICE_ENV:-development}
      APP_OTEL_EXPORTER_OTLP_ENDPOINT: ${COMMON_OTEL_EXPORTER_OTLP_ENDPOINT:-localhost:4317}
  opensearch:
    profiles:
      - dashboard
    image: public.ecr.aws/opensearchproject/opensearch:2.3.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - DISABLE_SECURITY_PLUGIN=true
      - DISABLE_INSTALL_DEMO_CONFIG=true
    volumes:
      - opensearch:/usr/share/opensearch/data
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  opensearch-dashboard:
    profiles:
      - dashboard
    image: public.ecr.aws/opensearchproject/opensearch-dashboards:2.3.0
    ports:
      - 5601:5601
    environment:
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]

volumes:
  mysql-db: {}
  opensearch: {}
