---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: safedep-gateway-pdp
    group: safedep
  name: safedep-gateway-pdp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: safedep-gateway-pdp
  template:
    metadata:
      labels:
        app: safedep-gateway-pdp
    spec:
      volumes:
      - name: gateway-config
        configMap:
          name: gateway-config
          items:
            - key: gateway.json
              path: gateway.json
            - key: envoy.json
              path: envoy.json
      - name: root-crt
        secret:
          secretName: pki-root-crt
          items:
            - key: root.crt
              path: root.crt
      - name: pdp-pki
        secret:
          secretName: pdp-pki
          items:
            - key: server.crt
              path: server.crt
            - key: server.key
              path: server.key
      - name: pdp-policies
        hostPath:
          path: /data/policies
          type: Directory
      containers:
      - name: safedep-gateway-pdp
        image: ghcr.io/safedep/gateway:latest
        command: [ "pdp-server" ]
        ports:
          - containerPort: 9000
        volumeMounts:
        - name: gateway-config
          mountPath: /config
          readOnly: true
        - name: pdp-pki
          mountPath: /config/pki
          readOnly: true
        - name: root-crt
          mountPath: /config/pki-root
          readOnly: true
        - name: pdp-policies
          mountPath: /data/policies
          readOnly: true
        env:
        - name: GLOBAL_CONFIG_PATH
          value: /config/gateway.json
        - name: SERVICE_TLS_CERT
          value: /config/pki/server.crt
        - name: SERVICE_TLS_KEY
          value: /config/pki/server.key
        - name: SERVICE_TLS_ROOT_CA
          value: /config/pki-root/root.crt
        - name: PDP_POLICY_PATH
          value: /data/policies
        resources:
          requests:
            memory: "64M"
            cpu: "100m"
          limits:
            memory: "128M"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: pdp
  labels:
    app: safedep-gateway-pdp
spec:
  ports:
  - port: 9000
    protocol: TCP
  selector:
    app: safedep-gateway-pdp

