apiVersion: v1
kind: PersistentVolume
metadata:
  name: minikube-volume
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/minikube-volume
    type: DirectoryOrCreate
